# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('type', models.CharField(max_length=60)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
                ('url', models.TextField()),
                ('external_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='s3images.ExternalImage')),
            ],
        ),
    ]
